# Generated by Django 5.2.17 on 2026-08-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_sistema', models.CharField(default='Gestão de Cadastros', max_length=150)),
                ('nome_instituicao', models.CharField(blank=True, max_length=200)),
                ('email_instituicao', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='configuracoes/')),
                ('menu_compacto', models.BooleanField(default=False)),
                ('animacoes_interface', models.BooleanField(default=True)),
                ('cadastrador_pode_criar', models.BooleanField(default=True)),
                ('cadastrador_pode_editar', models.BooleanField(default=True)),
                ('cadastrador_pode_excluir', models.BooleanField(default=False)),
                ('cadastrador_pode_ver_outros', models.BooleanField(default=False)),
                ('cadastrador_pode_exportar', models.BooleanField(default=False)),
                ('logout_automatico', models.BooleanField(default=True)),
                ('tempo_logout_minutos', models.PositiveIntegerField(default=30)),
                ('ultimo_backup', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do sistema',
                'verbose_name_plural': 'Configurações do sistema',
            },
        ),
    ]
