# Generated by Django 5.2.17 on 2026-08-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regioes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidade',
            name='tipo',
            field=models.CharField(choices=[('BAIRRO', 'Bairro'), ('COMUNIDADE', 'Comunidade'), ('DISTRITO', 'Distrito')], default='BAIRRO', max_length=20),
        ),
    ]
