# Generated by Django 5.2.17 on 2026-08-15 03:52

import django.db.models.deletion
import pessoas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_pessoa_cpf_pessoa_data_nascimento_and_more'),
        ('regioes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[pessoas.models.validar_cpf]),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='localidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pessoas', to='regioes.localidade'),
        ),
    ]
