# Generated by Django 5.2.17 on 2026-08-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0004_alter_pessoa_cpf_alter_pessoa_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='municipio_eleitoral',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='secao_eleitoral',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='zona_eleitoral',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
