# Generated by Django 5.2.17 on 2026-08-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0005_pessoa_municipio_eleitoral_pessoa_secao_eleitoral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadoEleitoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_eleitor', models.CharField(max_length=12, unique=True)),
                ('zona_eleitoral', models.CharField(max_length=10)),
                ('secao_eleitoral', models.CharField(max_length=10)),
                ('municipio_eleitoral', models.CharField(max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dado eleitoral',
                'verbose_name_plural': 'Dados eleitorais',
                'ordering': ['titulo_eleitor'],
            },
        ),
    ]
