# Generated by Django 5.2.17 on 2026-08-16 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0006_dadoeleitoral'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DadoEleitoral',
        ),
    ]
