# Generated by Django 5.2.17 on 2026-08-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0007_delete_dadoeleitoral'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
    ]
