# Generated by Django 5.2.17 on 2026-08-20 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0008_pessoa_cep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='cep',
        ),
    ]
