# Generated by Django 5.2.17 on 2026-08-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0009_remove_pessoa_cep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='municipio_eleitoral',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='secao_eleitoral',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='status_verificacao_titulo',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='titulo_eleitor',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='zona_eleitoral',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
