# Generated by Django 5.2.17 on 2026-08-26 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pessoas",
            "0010_remove_pessoa_municipio_eleitoral_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pessoa",
            name="nome_mae",
        ),

        migrations.RemoveField(
            model_name="pessoa",
            name="nome_pai",
        ),

        migrations.AddField(
            model_name="pessoa",
            name="municipio_eleitoral",
            field=models.CharField(
                blank=True,
                max_length=150,
            ),
        ),

        migrations.AddField(
            model_name="pessoa",
            name="secao_eleitoral",
            field=models.CharField(
                blank=True,
                max_length=10,
            ),
        ),

        migrations.AddField(
            model_name="pessoa",
            name="status_verificacao_titulo",
            field=models.CharField(
                choices=[
                    (
                        "NAO_VERIFICADO",
                        "Não verificado",
                    ),
                    (
                        "CONSULTADO",
                        "Consulta realizada",
                    ),
                ],
                default="NAO_VERIFICADO",
                max_length=20,
            ),
        ),

        migrations.AddField(
            model_name="pessoa",
            name="titulo_eleitor",
            field=models.CharField(
                blank=True,
                null=True,
                max_length=20,
                unique=True,
            ),
        ),

        migrations.AddField(
            model_name="pessoa",
            name="zona_eleitoral",
            field=models.CharField(
                blank=True,
                max_length=10,
            ),
        ),
    ]