# Generated by Django 5.2.17 on 2026-08-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0011_remove_pessoa_nome_mae_remove_pessoa_nome_pai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
