# Generated by Django 5.2.17 on 2026-09-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0012_pessoa_nome_mae_pessoa_nome_pai'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='candidato_deputado_estadual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='candidato_deputado_federal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='candidato_governador',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='candidato_senador',
            field=models.BooleanField(default=False),
        ),
    ]
