# Generated by Django 5.2.17 on 2026-08-15 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
        ('regioes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cadastrada_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pessoas_cadastradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='localidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pessoas', to='regioes.localidade'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='regiao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pessoas', to='regioes.regiao'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='rua',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pessoas', to='regioes.rua'),
        ),
    ]
