# Generated by Django 5.2.17 on 2026-08-15 03:38

import pessoas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, validators=[pessoas.models.validar_cpf]),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='status_verificacao_cpf',
            field=models.CharField(choices=[('NAO_VERIFICADO', 'Não verificado'), ('CONSULTADO', 'Consulta realizada')], default='NAO_VERIFICADO', max_length=20),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='status_verificacao_titulo',
            field=models.CharField(choices=[('NAO_VERIFICADO', 'Não verificado'), ('CONSULTADO', 'Consulta realizada')], default='NAO_VERIFICADO', max_length=20),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='titulo_eleitor',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
