# Generated by Django 5.2.17 on 2026-08-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoria',
            name='acao',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CRIACAO', 'Criação'), ('ALTERACAO', 'Alteração'), ('EXCLUSAO', 'Exclusão'), ('ATIVACAO', 'Ativação'), ('DESATIVACAO', 'Desativação'), ('CONSULTA', 'Consulta')], max_length=20),
        ),
    ]
